### ISSUE TITLE
Underscore SortBy is acting funky

### ISSUE THREAD

**Issue by SamMatthews9** [SamMatthews9/Timelin.R#17]
Hello!
For my card game I am using two versions of my primary cards.collection:
The shuffledCollection takes a random sample of 5 models from this collection.
And I want the orderedCollection to be a sorted version of the the shuffledCollection (by year).
 
It's possible that I could do this, by declaring what five cards are being used, then sampling or shuffling that, but I'd much rather have it done this way, so the cards are random each time.  
The current method I am using, is re-sorting the cards, but not chronologically. Other sorting algorithms I tried just returned the orderedCollection 
 		orderedCollection = _.sortBy(shuffledCollection, $('.year').val());

I have tried a few different sorting algorithms, but am still confused by sorting an array of models, as opposed to normal elements.

Thank you!
@harimohanraj89 @htella @DrRobotmck

**Comment by DrRobotmck** [comment]
That `sortBy` function needs two parameters: first, the collection you'd like to sort (which you provide), second, a function that you would like to use to sort it by. Here it looks like you're giving it a value, as opposed to some callback that sortBy should use to sort the collection. Take a look at the `sortBy` function and how it's being used in the underscore docs one more time.

**Comment by SamMatthews9** [comment]
I got it working with a simple function being passed to it, thanks!
