### ISSUE TITLE
Backbone Issues

### ISSUE THREAD

**Issue by SamMatthews9** [SamMatthews9/Timelin.R#7]
I am having some issues with Backbone. This morning I completely scrapped what I had been working on over the weekend, which integrated users and sessions, and simplified it to focus solely on the game's playing cards.
I am passing the cards collection into the cardView, but when I try to pass each item in the collection, it is not identifying the collection. I'd like to meet with one of you to discuss some of the backbone conventions and to ask a few specifics about how the app is currently set up.  Especially, about using backbone with additional rails routes/views.  If I can't figure this out, I'm thinking I'll just revert back to a normal assets/javascript file, since I'm more familiar with that way of things, but I really do want to get a better understanding of backbone!

Thank yous
@harimohanraj89 @htella @DrRobotmck

**Comment by htella** [comment]
Got this.

**Comment by htella** [comment]
What do you mean by ''not identifying the collection"

**Comment by SamMatthews9** [comment]
When I pass it in (last line of the render: function, below), the program
never makes it to the renderCard function.
even though I explicitly give it the collection here: App.cardListView =
new App.Views.CardsListView({ collection: App.cards });

render: function() {
console.log('render card list view');
this.$el.empty();
console.log(this.collection);
this.collection.each(this.renderCard, this);
},

renderCard: function(card) {
console.log("rendering card, making cardView");
var cardView = new App.Views.CardView({ model: card });
this.$el.append(cardView.$el);
}

**Comment by htella** [comment]
Can you push your latest code.

**Comment by htella** [comment]
Also try swapping these two lines in application.js

```ruby
App.cards.fetch({ reset: true });
App.cardsView = new App.Views.CardView({ collection: App.cards });	
```

so fetch comes after

```ruby
App.cardsView = new App.Views.CardView({ collection: App.cards });	
App.cards.fetch({ reset: true });
```

**Comment by SamMatthews9** [comment]
Sure, just pushed it.

**Comment by htella** [comment]
any luck with my suggestion

**Comment by SamMatthews9** [comment]
No, already thought that was an issue.

**Comment by htella** [comment]
In your CardView.js

```javascript
	render: function() {
		console.log("rendering cards");
		this.$el.empty();	
		this.collection.each(this.renderCards, this);
	},

	renderCards: function(card) {
		console.log("*******");
		this.$el.append(el);
	}
```

your CardView should be dealing with a model not a collection.

**Comment by SamMatthews9** [comment]
I also tried doing, App.this.collection.fetch() above the .each function,
but it still returns an empty collection.  In the console, with debugger I
have been able to get the collection to properly fetch, but not when I try
to apply that to the View file

**Comment by SamMatthews9** [comment]
I'm not using the CardView.js right now, pretty sure I only need one view,
so I've been running (nearly) identical files between CardView and
CardListView

**Comment by htella** [comment]
Are you still waiting to be interviewed, otherwise we can talk.

**Comment by htella** [comment]
Or I can meet you downstairs.

**Comment by SamMatthews9** [comment]
No, I've been interviewed.  Happy to talk, where are you?

**Comment by htella** [comment]
in the classroom
